// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otkhkhqtumpbvpablzaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90a2hraHF0dW1wYnZwYWJsemF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMjAzNDAsImV4cCI6MjA3NDY5NjM0MH0.aQIw-QumSdTWFRIHoLUqmMpEIDp9NwtIJMLtttTN6N4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});